#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AEROLINEA")]
	public partial class BaseDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertADMINISTRADOR(ADMINISTRADOR instance);
    partial void UpdateADMINISTRADOR(ADMINISTRADOR instance);
    partial void DeleteADMINISTRADOR(ADMINISTRADOR instance);
    partial void InsertVUELOS(VUELOS instance);
    partial void UpdateVUELOS(VUELOS instance);
    partial void DeleteVUELOS(VUELOS instance);
    partial void InsertAERONAVES(AERONAVES instance);
    partial void UpdateAERONAVES(AERONAVES instance);
    partial void DeleteAERONAVES(AERONAVES instance);
    partial void InsertPASAJEROS(PASAJEROS instance);
    partial void UpdatePASAJEROS(PASAJEROS instance);
    partial void DeletePASAJEROS(PASAJEROS instance);
    partial void InsertPILOTOS(PILOTOS instance);
    partial void UpdatePILOTOS(PILOTOS instance);
    partial void DeletePILOTOS(PILOTOS instance);
    partial void InsertTICKET(TICKET instance);
    partial void UpdateTICKET(TICKET instance);
    partial void DeleteTICKET(TICKET instance);
    partial void InsertTRAYECTOS(TRAYECTOS instance);
    partial void UpdateTRAYECTOS(TRAYECTOS instance);
    partial void DeleteTRAYECTOS(TRAYECTOS instance);
    partial void InsertVOLETO(VOLETO instance);
    partial void UpdateVOLETO(VOLETO instance);
    partial void DeleteVOLETO(VOLETO instance);
    #endregion
		
		public BaseDatosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AEROLINEAConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMINISTRADOR> ADMINISTRADOR
		{
			get
			{
				return this.GetTable<ADMINISTRADOR>();
			}
		}
		
		public System.Data.Linq.Table<VUELOS> VUELOS
		{
			get
			{
				return this.GetTable<VUELOS>();
			}
		}
		
		public System.Data.Linq.Table<AERONAVES> AERONAVES
		{
			get
			{
				return this.GetTable<AERONAVES>();
			}
		}
		
		public System.Data.Linq.Table<PASAJEROS> PASAJEROS
		{
			get
			{
				return this.GetTable<PASAJEROS>();
			}
		}
		
		public System.Data.Linq.Table<PILOTOS> PILOTOS
		{
			get
			{
				return this.GetTable<PILOTOS>();
			}
		}
		
		public System.Data.Linq.Table<TICKET> TICKET
		{
			get
			{
				return this.GetTable<TICKET>();
			}
		}
		
		public System.Data.Linq.Table<TRAYECTOS> TRAYECTOS
		{
			get
			{
				return this.GetTable<TRAYECTOS>();
			}
		}
		
		public System.Data.Linq.Table<VOLETO> VOLETO
		{
			get
			{
				return this.GetTable<VOLETO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAsientos", IsComposable=true)]
		public System.Nullable<int> getAsientos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTicket)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTicket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getUnidades", IsComposable=true)]
		public System.Nullable<int> getUnidades([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAutonomia", IsComposable=true)]
		public System.Nullable<int> getAutonomia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCarga", IsComposable=true)]
		public System.Nullable<double> getCarga([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ticket)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ticket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDuracion", IsComposable=true)]
		public System.Nullable<int> getDuracion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getFechaViaje", IsComposable=true)]
		public System.Nullable<System.DateTime> getFechaViaje([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket)
		{
			return ((System.Nullable<System.DateTime>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTicket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHoras", IsComposable=true)]
		public string getHoras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seconds)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), seconds).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getIdPasajero", IsComposable=true)]
		public string getIdPasajero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getMillas", IsComposable=true)]
		public System.Nullable<int> getMillas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTicket)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTicket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getMillasPasajero", IsComposable=true)]
		public System.Nullable<int> getMillasPasajero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPesoTicket", IsComposable=true)]
		public System.Nullable<int> getPesoTicket([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ticket)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ticket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPrecio", IsComposable=true)]
		public System.Nullable<decimal> getPrecio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTicket)
		{
			return ((System.Nullable<decimal>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTicket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTemporada", IsComposable=true)]
		public string getTemporada([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTicket)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTicket).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTime", IsComposable=true)]
		public string getTime([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seconds)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), seconds).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.clientesFrecuentes")]
		public ISingleResult<clientesFrecuentesResult> clientesFrecuentes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] ref string numeroClientes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroClientes);
			numeroClientes = ((string)(result.GetParameterValue(0)));
			return ((ISingleResult<clientesFrecuentesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vuelosPiloto")]
		public ISingleResult<vuelosPilotoResult> vuelosPiloto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario);
			return ((ISingleResult<vuelosPilotoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.clientesIdaVuelta")]
		public ISingleResult<clientesIdaVueltaResult> clientesIdaVuelta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] ref string numeroClientes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroClientes);
			numeroClientes = ((string)(result.GetParameterValue(0)));
			return ((ISingleResult<clientesIdaVueltaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarVuelos")]
		public ISingleResult<listarVuelosResult> listarVuelos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarVuelosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarVuelosRegistro")]
		public ISingleResult<listarVuelosRegistroResult> listarVuelosRegistro()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarVuelosRegistroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarAdministrador")]
		public int registrarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contrasenia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, usuario, contrasenia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarAeronave")]
		public int registrarAeronave([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAeronave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string licencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pasajeros, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> carga, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> autonomia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAeronave, tipo, licencia, pasajeros, carga, autonomia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarPasajero")]
		public int registrarPasajero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string identificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contrasenia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> millas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> frecuente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificacion, nombre, usuario, contrasenia, millas, frecuente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarPiloto")]
		public int registrarPiloto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contrasenia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> horasVuelo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, usuario, contrasenia, horasVuelo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarTicket")]
		public ISingleResult<registrarTicketResult> registrarTicket([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTiquete, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAeronave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string piloto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVuelo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(64)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTiquete, idAeronave, piloto, idVuelo, mensaje);
			mensaje = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<registrarTicketResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarTrayecto")]
		public int registrarTrayecto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string idTrayecto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(32)")] string origen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(32)")] string destino, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precioBase, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> duracion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTrayecto, origen, destino, precioBase, descuento, duracion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarVoleto")]
		public int registrarVoleto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string pasajero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> valor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> idaVuelta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ticketIda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ticketRegreso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> peso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pasajero, valor, idaVuelta, ticketIda, ticketRegreso, peso, mensaje);
			mensaje = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarVuelo")]
		public int registrarVuelo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVuelo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaHoraViaje, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(16)")] string temporada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string idAdmin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string trayecto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVuelo, fechaHoraViaje, temporada, idAdmin, trayecto, mensaje);
			mensaje = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.restablecerAutonomia")]
		public int restablecerAutonomia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAeronave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idAeronave, mensaje);
			mensaje = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setAsientos")]
		public int setAsientos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTicket);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setAutonomia")]
		public int setAutonomia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAeronave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> duracion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAeronave, duracion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setMillas")]
		public int setMillas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> millas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, millas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setPesoEquipaje")]
		public int setPesoEquipaje([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> peso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTicket, peso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sumarHorasVuelo")]
		public int sumarHorasVuelo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string trayecto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, trayecto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vuelosPasajero")]
		public ISingleResult<vuelosPasajeroResult> vuelosPasajero()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<vuelosPasajeroResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMINISTRADOR")]
	public partial class ADMINISTRADOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Contrasenia;
		
		private EntitySet<VUELOS> _VUELOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseniaChanging(string value);
    partial void OnContraseniaChanged();
    #endregion
		
		public ADMINISTRADOR()
		{
			this._VUELOS = new EntitySet<VUELOS>(new Action<VUELOS>(this.attach_VUELOS), new Action<VUELOS>(this.detach_VUELOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Contrasenia
		{
			get
			{
				return this._Contrasenia;
			}
			set
			{
				if ((this._Contrasenia != value))
				{
					this.OnContraseniaChanging(value);
					this.SendPropertyChanging();
					this._Contrasenia = value;
					this.SendPropertyChanged("Contrasenia");
					this.OnContraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMINISTRADOR_VUELOS", Storage="_VUELOS", ThisKey="Usuario", OtherKey="IdAdmin")]
		public EntitySet<VUELOS> VUELOS
		{
			get
			{
				return this._VUELOS;
			}
			set
			{
				this._VUELOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VUELOS(VUELOS entity)
		{
			this.SendPropertyChanging();
			entity.ADMINISTRADOR = this;
		}
		
		private void detach_VUELOS(VUELOS entity)
		{
			this.SendPropertyChanging();
			entity.ADMINISTRADOR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VUELOS")]
	public partial class VUELOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVuelo;
		
		private System.DateTime _FechaHoraViaje;
		
		private string _Temporada;
		
		private string _IdAdmin;
		
		private string _Trayecto;
		
		private EntitySet<TICKET> _TICKET;
		
		private EntityRef<ADMINISTRADOR> _ADMINISTRADOR;
		
		private EntityRef<TRAYECTOS> _TRAYECTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVueloChanging(int value);
    partial void OnIdVueloChanged();
    partial void OnFechaHoraViajeChanging(System.DateTime value);
    partial void OnFechaHoraViajeChanged();
    partial void OnTemporadaChanging(string value);
    partial void OnTemporadaChanged();
    partial void OnIdAdminChanging(string value);
    partial void OnIdAdminChanged();
    partial void OnTrayectoChanging(string value);
    partial void OnTrayectoChanged();
    #endregion
		
		public VUELOS()
		{
			this._TICKET = new EntitySet<TICKET>(new Action<TICKET>(this.attach_TICKET), new Action<TICKET>(this.detach_TICKET));
			this._ADMINISTRADOR = default(EntityRef<ADMINISTRADOR>);
			this._TRAYECTOS = default(EntityRef<TRAYECTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVuelo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdVuelo
		{
			get
			{
				return this._IdVuelo;
			}
			set
			{
				if ((this._IdVuelo != value))
				{
					this.OnIdVueloChanging(value);
					this.SendPropertyChanging();
					this._IdVuelo = value;
					this.SendPropertyChanged("IdVuelo");
					this.OnIdVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraViaje", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraViaje
		{
			get
			{
				return this._FechaHoraViaje;
			}
			set
			{
				if ((this._FechaHoraViaje != value))
				{
					this.OnFechaHoraViajeChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraViaje = value;
					this.SendPropertyChanged("FechaHoraViaje");
					this.OnFechaHoraViajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporada", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Temporada
		{
			get
			{
				return this._Temporada;
			}
			set
			{
				if ((this._Temporada != value))
				{
					this.OnTemporadaChanging(value);
					this.SendPropertyChanging();
					this._Temporada = value;
					this.SendPropertyChanged("Temporada");
					this.OnTemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdmin", DbType="VarChar(20)")]
		public string IdAdmin
		{
			get
			{
				return this._IdAdmin;
			}
			set
			{
				if ((this._IdAdmin != value))
				{
					if (this._ADMINISTRADOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAdminChanging(value);
					this.SendPropertyChanging();
					this._IdAdmin = value;
					this.SendPropertyChanged("IdAdmin");
					this.OnIdAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trayecto", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Trayecto
		{
			get
			{
				return this._Trayecto;
			}
			set
			{
				if ((this._Trayecto != value))
				{
					if (this._TRAYECTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTrayectoChanging(value);
					this.SendPropertyChanging();
					this._Trayecto = value;
					this.SendPropertyChanged("Trayecto");
					this.OnTrayectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VUELOS_TICKET", Storage="_TICKET", ThisKey="IdVuelo", OtherKey="IdVuelo")]
		public EntitySet<TICKET> TICKET
		{
			get
			{
				return this._TICKET;
			}
			set
			{
				this._TICKET.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMINISTRADOR_VUELOS", Storage="_ADMINISTRADOR", ThisKey="IdAdmin", OtherKey="Usuario", IsForeignKey=true)]
		public ADMINISTRADOR ADMINISTRADOR
		{
			get
			{
				return this._ADMINISTRADOR.Entity;
			}
			set
			{
				ADMINISTRADOR previousValue = this._ADMINISTRADOR.Entity;
				if (((previousValue != value) 
							|| (this._ADMINISTRADOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADMINISTRADOR.Entity = null;
						previousValue.VUELOS.Remove(this);
					}
					this._ADMINISTRADOR.Entity = value;
					if ((value != null))
					{
						value.VUELOS.Add(this);
						this._IdAdmin = value.Usuario;
					}
					else
					{
						this._IdAdmin = default(string);
					}
					this.SendPropertyChanged("ADMINISTRADOR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAYECTOS_VUELOS", Storage="_TRAYECTOS", ThisKey="Trayecto", OtherKey="IdTrayecto", IsForeignKey=true)]
		public TRAYECTOS TRAYECTOS
		{
			get
			{
				return this._TRAYECTOS.Entity;
			}
			set
			{
				TRAYECTOS previousValue = this._TRAYECTOS.Entity;
				if (((previousValue != value) 
							|| (this._TRAYECTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAYECTOS.Entity = null;
						previousValue.VUELOS.Remove(this);
					}
					this._TRAYECTOS.Entity = value;
					if ((value != null))
					{
						value.VUELOS.Add(this);
						this._Trayecto = value.IdTrayecto;
					}
					else
					{
						this._Trayecto = default(string);
					}
					this.SendPropertyChanged("TRAYECTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.VUELOS = this;
		}
		
		private void detach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.VUELOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AERONAVES")]
	public partial class AERONAVES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAeronave;
		
		private string _Tipo;
		
		private string _Licencia;
		
		private int _Pasajeros;
		
		private double _Carga;
		
		private System.Nullable<int> _Unidades;
		
		private System.Nullable<System.TimeSpan> _Autonomia;
		
		private EntitySet<TICKET> _TICKET;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAeronaveChanging(int value);
    partial void OnIdAeronaveChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnLicenciaChanging(string value);
    partial void OnLicenciaChanged();
    partial void OnPasajerosChanging(int value);
    partial void OnPasajerosChanged();
    partial void OnCargaChanging(double value);
    partial void OnCargaChanged();
    partial void OnUnidadesChanging(System.Nullable<int> value);
    partial void OnUnidadesChanged();
    partial void OnAutonomiaChanging(System.Nullable<System.TimeSpan> value);
    partial void OnAutonomiaChanged();
    #endregion
		
		public AERONAVES()
		{
			this._TICKET = new EntitySet<TICKET>(new Action<TICKET>(this.attach_TICKET), new Action<TICKET>(this.detach_TICKET));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAeronave", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdAeronave
		{
			get
			{
				return this._IdAeronave;
			}
			set
			{
				if ((this._IdAeronave != value))
				{
					this.OnIdAeronaveChanging(value);
					this.SendPropertyChanging();
					this._IdAeronave = value;
					this.SendPropertyChanged("IdAeronave");
					this.OnIdAeronaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Licencia", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Licencia
		{
			get
			{
				return this._Licencia;
			}
			set
			{
				if ((this._Licencia != value))
				{
					this.OnLicenciaChanging(value);
					this.SendPropertyChanging();
					this._Licencia = value;
					this.SendPropertyChanged("Licencia");
					this.OnLicenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasajeros", DbType="Int NOT NULL")]
		public int Pasajeros
		{
			get
			{
				return this._Pasajeros;
			}
			set
			{
				if ((this._Pasajeros != value))
				{
					this.OnPasajerosChanging(value);
					this.SendPropertyChanging();
					this._Pasajeros = value;
					this.SendPropertyChanged("Pasajeros");
					this.OnPasajerosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carga", DbType="Float NOT NULL")]
		public double Carga
		{
			get
			{
				return this._Carga;
			}
			set
			{
				if ((this._Carga != value))
				{
					this.OnCargaChanging(value);
					this.SendPropertyChanging();
					this._Carga = value;
					this.SendPropertyChanged("Carga");
					this.OnCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidades", DbType="Int")]
		public System.Nullable<int> Unidades
		{
			get
			{
				return this._Unidades;
			}
			set
			{
				if ((this._Unidades != value))
				{
					this.OnUnidadesChanging(value);
					this.SendPropertyChanging();
					this._Unidades = value;
					this.SendPropertyChanged("Unidades");
					this.OnUnidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autonomia", DbType="Time")]
		public System.Nullable<System.TimeSpan> Autonomia
		{
			get
			{
				return this._Autonomia;
			}
			set
			{
				if ((this._Autonomia != value))
				{
					this.OnAutonomiaChanging(value);
					this.SendPropertyChanging();
					this._Autonomia = value;
					this.SendPropertyChanged("Autonomia");
					this.OnAutonomiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AERONAVES_TICKET", Storage="_TICKET", ThisKey="IdAeronave", OtherKey="IdAeronave")]
		public EntitySet<TICKET> TICKET
		{
			get
			{
				return this._TICKET;
			}
			set
			{
				this._TICKET.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.AERONAVES = this;
		}
		
		private void detach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.AERONAVES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PASAJEROS")]
	public partial class PASAJEROS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Identificacion;
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Contrasenia;
		
		private System.Nullable<int> _Millas;
		
		private System.Nullable<bool> _Frecuente;
		
		private EntitySet<VOLETO> _VOLETO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificacionChanging(string value);
    partial void OnIdentificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseniaChanging(string value);
    partial void OnContraseniaChanged();
    partial void OnMillasChanging(System.Nullable<int> value);
    partial void OnMillasChanged();
    partial void OnFrecuenteChanging(System.Nullable<bool> value);
    partial void OnFrecuenteChanged();
    #endregion
		
		public PASAJEROS()
		{
			this._VOLETO = new EntitySet<VOLETO>(new Action<VOLETO>(this.attach_VOLETO), new Action<VOLETO>(this.detach_VOLETO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Contrasenia
		{
			get
			{
				return this._Contrasenia;
			}
			set
			{
				if ((this._Contrasenia != value))
				{
					this.OnContraseniaChanging(value);
					this.SendPropertyChanging();
					this._Contrasenia = value;
					this.SendPropertyChanged("Contrasenia");
					this.OnContraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Millas", DbType="Int")]
		public System.Nullable<int> Millas
		{
			get
			{
				return this._Millas;
			}
			set
			{
				if ((this._Millas != value))
				{
					this.OnMillasChanging(value);
					this.SendPropertyChanging();
					this._Millas = value;
					this.SendPropertyChanged("Millas");
					this.OnMillasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuente", DbType="Bit")]
		public System.Nullable<bool> Frecuente
		{
			get
			{
				return this._Frecuente;
			}
			set
			{
				if ((this._Frecuente != value))
				{
					this.OnFrecuenteChanging(value);
					this.SendPropertyChanging();
					this._Frecuente = value;
					this.SendPropertyChanged("Frecuente");
					this.OnFrecuenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PASAJEROS_VOLETO", Storage="_VOLETO", ThisKey="Identificacion", OtherKey="Pasajero")]
		public EntitySet<VOLETO> VOLETO
		{
			get
			{
				return this._VOLETO;
			}
			set
			{
				this._VOLETO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VOLETO(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.PASAJEROS = this;
		}
		
		private void detach_VOLETO(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.PASAJEROS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PILOTOS")]
	public partial class PILOTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Contrasenia;
		
		private double _HorasVuelo;
		
		private EntitySet<TICKET> _TICKET;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseniaChanging(string value);
    partial void OnContraseniaChanged();
    partial void OnHorasVueloChanging(double value);
    partial void OnHorasVueloChanged();
    #endregion
		
		public PILOTOS()
		{
			this._TICKET = new EntitySet<TICKET>(new Action<TICKET>(this.attach_TICKET), new Action<TICKET>(this.detach_TICKET));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Contrasenia
		{
			get
			{
				return this._Contrasenia;
			}
			set
			{
				if ((this._Contrasenia != value))
				{
					this.OnContraseniaChanging(value);
					this.SendPropertyChanging();
					this._Contrasenia = value;
					this.SendPropertyChanged("Contrasenia");
					this.OnContraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasVuelo", DbType="Float NOT NULL")]
		public double HorasVuelo
		{
			get
			{
				return this._HorasVuelo;
			}
			set
			{
				if ((this._HorasVuelo != value))
				{
					this.OnHorasVueloChanging(value);
					this.SendPropertyChanging();
					this._HorasVuelo = value;
					this.SendPropertyChanged("HorasVuelo");
					this.OnHorasVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILOTOS_TICKET", Storage="_TICKET", ThisKey="Usuario", OtherKey="Piloto")]
		public EntitySet<TICKET> TICKET
		{
			get
			{
				return this._TICKET;
			}
			set
			{
				this._TICKET.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PILOTOS = this;
		}
		
		private void detach_TICKET(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PILOTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TICKET")]
	public partial class TICKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoTicket;
		
		private int _IdAeronave;
		
		private string _Piloto;
		
		private int _IdVuelo;
		
		private System.Nullable<int> _PesoEquipaje;
		
		private System.Nullable<int> _Asientos;
		
		private EntitySet<VOLETO> _VOLETO;
		
		private EntitySet<VOLETO> _VOLETO1;
		
		private EntityRef<AERONAVES> _AERONAVES;
		
		private EntityRef<PILOTOS> _PILOTOS;
		
		private EntityRef<VUELOS> _VUELOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoTicketChanging(int value);
    partial void OnCodigoTicketChanged();
    partial void OnIdAeronaveChanging(int value);
    partial void OnIdAeronaveChanged();
    partial void OnPilotoChanging(string value);
    partial void OnPilotoChanged();
    partial void OnIdVueloChanging(int value);
    partial void OnIdVueloChanged();
    partial void OnPesoEquipajeChanging(System.Nullable<int> value);
    partial void OnPesoEquipajeChanged();
    partial void OnAsientosChanging(System.Nullable<int> value);
    partial void OnAsientosChanged();
    #endregion
		
		public TICKET()
		{
			this._VOLETO = new EntitySet<VOLETO>(new Action<VOLETO>(this.attach_VOLETO), new Action<VOLETO>(this.detach_VOLETO));
			this._VOLETO1 = new EntitySet<VOLETO>(new Action<VOLETO>(this.attach_VOLETO1), new Action<VOLETO>(this.detach_VOLETO1));
			this._AERONAVES = default(EntityRef<AERONAVES>);
			this._PILOTOS = default(EntityRef<PILOTOS>);
			this._VUELOS = default(EntityRef<VUELOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTicket", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoTicket
		{
			get
			{
				return this._CodigoTicket;
			}
			set
			{
				if ((this._CodigoTicket != value))
				{
					this.OnCodigoTicketChanging(value);
					this.SendPropertyChanging();
					this._CodigoTicket = value;
					this.SendPropertyChanged("CodigoTicket");
					this.OnCodigoTicketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAeronave", DbType="Int NOT NULL")]
		public int IdAeronave
		{
			get
			{
				return this._IdAeronave;
			}
			set
			{
				if ((this._IdAeronave != value))
				{
					if (this._AERONAVES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAeronaveChanging(value);
					this.SendPropertyChanging();
					this._IdAeronave = value;
					this.SendPropertyChanged("IdAeronave");
					this.OnIdAeronaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piloto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Piloto
		{
			get
			{
				return this._Piloto;
			}
			set
			{
				if ((this._Piloto != value))
				{
					if (this._PILOTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPilotoChanging(value);
					this.SendPropertyChanging();
					this._Piloto = value;
					this.SendPropertyChanged("Piloto");
					this.OnPilotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVuelo", DbType="Int NOT NULL")]
		public int IdVuelo
		{
			get
			{
				return this._IdVuelo;
			}
			set
			{
				if ((this._IdVuelo != value))
				{
					if (this._VUELOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVueloChanging(value);
					this.SendPropertyChanging();
					this._IdVuelo = value;
					this.SendPropertyChanged("IdVuelo");
					this.OnIdVueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoEquipaje", DbType="Int")]
		public System.Nullable<int> PesoEquipaje
		{
			get
			{
				return this._PesoEquipaje;
			}
			set
			{
				if ((this._PesoEquipaje != value))
				{
					this.OnPesoEquipajeChanging(value);
					this.SendPropertyChanging();
					this._PesoEquipaje = value;
					this.SendPropertyChanged("PesoEquipaje");
					this.OnPesoEquipajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asientos", DbType="Int")]
		public System.Nullable<int> Asientos
		{
			get
			{
				return this._Asientos;
			}
			set
			{
				if ((this._Asientos != value))
				{
					this.OnAsientosChanging(value);
					this.SendPropertyChanging();
					this._Asientos = value;
					this.SendPropertyChanged("Asientos");
					this.OnAsientosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TICKET_VOLETO", Storage="_VOLETO", ThisKey="CodigoTicket", OtherKey="TicketIda")]
		public EntitySet<VOLETO> VOLETO
		{
			get
			{
				return this._VOLETO;
			}
			set
			{
				this._VOLETO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TICKET_VOLETO1", Storage="_VOLETO1", ThisKey="CodigoTicket", OtherKey="TicketRegreso")]
		public EntitySet<VOLETO> VOLETO1
		{
			get
			{
				return this._VOLETO1;
			}
			set
			{
				this._VOLETO1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AERONAVES_TICKET", Storage="_AERONAVES", ThisKey="IdAeronave", OtherKey="IdAeronave", IsForeignKey=true)]
		public AERONAVES AERONAVES
		{
			get
			{
				return this._AERONAVES.Entity;
			}
			set
			{
				AERONAVES previousValue = this._AERONAVES.Entity;
				if (((previousValue != value) 
							|| (this._AERONAVES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AERONAVES.Entity = null;
						previousValue.TICKET.Remove(this);
					}
					this._AERONAVES.Entity = value;
					if ((value != null))
					{
						value.TICKET.Add(this);
						this._IdAeronave = value.IdAeronave;
					}
					else
					{
						this._IdAeronave = default(int);
					}
					this.SendPropertyChanged("AERONAVES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILOTOS_TICKET", Storage="_PILOTOS", ThisKey="Piloto", OtherKey="Usuario", IsForeignKey=true)]
		public PILOTOS PILOTOS
		{
			get
			{
				return this._PILOTOS.Entity;
			}
			set
			{
				PILOTOS previousValue = this._PILOTOS.Entity;
				if (((previousValue != value) 
							|| (this._PILOTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILOTOS.Entity = null;
						previousValue.TICKET.Remove(this);
					}
					this._PILOTOS.Entity = value;
					if ((value != null))
					{
						value.TICKET.Add(this);
						this._Piloto = value.Usuario;
					}
					else
					{
						this._Piloto = default(string);
					}
					this.SendPropertyChanged("PILOTOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VUELOS_TICKET", Storage="_VUELOS", ThisKey="IdVuelo", OtherKey="IdVuelo", IsForeignKey=true)]
		public VUELOS VUELOS
		{
			get
			{
				return this._VUELOS.Entity;
			}
			set
			{
				VUELOS previousValue = this._VUELOS.Entity;
				if (((previousValue != value) 
							|| (this._VUELOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VUELOS.Entity = null;
						previousValue.TICKET.Remove(this);
					}
					this._VUELOS.Entity = value;
					if ((value != null))
					{
						value.TICKET.Add(this);
						this._IdVuelo = value.IdVuelo;
					}
					else
					{
						this._IdVuelo = default(int);
					}
					this.SendPropertyChanged("VUELOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VOLETO(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.TICKET = this;
		}
		
		private void detach_VOLETO(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.TICKET = null;
		}
		
		private void attach_VOLETO1(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.TICKET1 = this;
		}
		
		private void detach_VOLETO1(VOLETO entity)
		{
			this.SendPropertyChanging();
			entity.TICKET1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRAYECTOS")]
	public partial class TRAYECTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTrayecto;
		
		private string _Origen;
		
		private string _Destino;
		
		private decimal _PrecioBase;
		
		private System.Nullable<int> _Descuento;
		
		private System.TimeSpan _Duracion;
		
		private EntitySet<VUELOS> _VUELOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTrayectoChanging(string value);
    partial void OnIdTrayectoChanged();
    partial void OnOrigenChanging(string value);
    partial void OnOrigenChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    partial void OnPrecioBaseChanging(decimal value);
    partial void OnPrecioBaseChanged();
    partial void OnDescuentoChanging(System.Nullable<int> value);
    partial void OnDescuentoChanged();
    partial void OnDuracionChanging(System.TimeSpan value);
    partial void OnDuracionChanged();
    #endregion
		
		public TRAYECTOS()
		{
			this._VUELOS = new EntitySet<VUELOS>(new Action<VUELOS>(this.attach_VUELOS), new Action<VUELOS>(this.detach_VUELOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTrayecto", DbType="VarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTrayecto
		{
			get
			{
				return this._IdTrayecto;
			}
			set
			{
				if ((this._IdTrayecto != value))
				{
					this.OnIdTrayectoChanging(value);
					this.SendPropertyChanging();
					this._IdTrayecto = value;
					this.SendPropertyChanged("IdTrayecto");
					this.OnIdTrayectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this.OnOrigenChanging(value);
					this.SendPropertyChanging();
					this._Origen = value;
					this.SendPropertyChanged("Origen");
					this.OnOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioBase", DbType="Money NOT NULL")]
		public decimal PrecioBase
		{
			get
			{
				return this._PrecioBase;
			}
			set
			{
				if ((this._PrecioBase != value))
				{
					this.OnPrecioBaseChanging(value);
					this.SendPropertyChanging();
					this._PrecioBase = value;
					this.SendPropertyChanged("PrecioBase");
					this.OnPrecioBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Int")]
		public System.Nullable<int> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this.OnDescuentoChanging(value);
					this.SendPropertyChanging();
					this._Descuento = value;
					this.SendPropertyChanged("Descuento");
					this.OnDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="Time NOT NULL")]
		public System.TimeSpan Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this.OnDuracionChanging(value);
					this.SendPropertyChanging();
					this._Duracion = value;
					this.SendPropertyChanged("Duracion");
					this.OnDuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAYECTOS_VUELOS", Storage="_VUELOS", ThisKey="IdTrayecto", OtherKey="Trayecto")]
		public EntitySet<VUELOS> VUELOS
		{
			get
			{
				return this._VUELOS;
			}
			set
			{
				this._VUELOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VUELOS(VUELOS entity)
		{
			this.SendPropertyChanging();
			entity.TRAYECTOS = this;
		}
		
		private void detach_VUELOS(VUELOS entity)
		{
			this.SendPropertyChanging();
			entity.TRAYECTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VOLETO")]
	public partial class VOLETO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Pasajero;
		
		private decimal _Valor;
		
		private System.Nullable<bool> _IdaVuelta;
		
		private int _TicketIda;
		
		private System.Nullable<int> _TicketRegreso;
		
		private double _PesoEquipaje;
		
		private int _IdVoleto;
		
		private EntityRef<TICKET> _TICKET;
		
		private EntityRef<PASAJEROS> _PASAJEROS;
		
		private EntityRef<TICKET> _TICKET1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPasajeroChanging(string value);
    partial void OnPasajeroChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnIdaVueltaChanging(System.Nullable<bool> value);
    partial void OnIdaVueltaChanged();
    partial void OnTicketIdaChanging(int value);
    partial void OnTicketIdaChanged();
    partial void OnTicketRegresoChanging(System.Nullable<int> value);
    partial void OnTicketRegresoChanged();
    partial void OnPesoEquipajeChanging(double value);
    partial void OnPesoEquipajeChanged();
    partial void OnIdVoletoChanging(int value);
    partial void OnIdVoletoChanged();
    #endregion
		
		public VOLETO()
		{
			this._TICKET = default(EntityRef<TICKET>);
			this._PASAJEROS = default(EntityRef<PASAJEROS>);
			this._TICKET1 = default(EntityRef<TICKET>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasajero", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Pasajero
		{
			get
			{
				return this._Pasajero;
			}
			set
			{
				if ((this._Pasajero != value))
				{
					if (this._PASAJEROS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPasajeroChanging(value);
					this.SendPropertyChanging();
					this._Pasajero = value;
					this.SendPropertyChanged("Pasajero");
					this.OnPasajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Money NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdaVuelta", DbType="Bit")]
		public System.Nullable<bool> IdaVuelta
		{
			get
			{
				return this._IdaVuelta;
			}
			set
			{
				if ((this._IdaVuelta != value))
				{
					this.OnIdaVueltaChanging(value);
					this.SendPropertyChanging();
					this._IdaVuelta = value;
					this.SendPropertyChanged("IdaVuelta");
					this.OnIdaVueltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketIda", DbType="Int NOT NULL")]
		public int TicketIda
		{
			get
			{
				return this._TicketIda;
			}
			set
			{
				if ((this._TicketIda != value))
				{
					if (this._TICKET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTicketIdaChanging(value);
					this.SendPropertyChanging();
					this._TicketIda = value;
					this.SendPropertyChanged("TicketIda");
					this.OnTicketIdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketRegreso", DbType="Int")]
		public System.Nullable<int> TicketRegreso
		{
			get
			{
				return this._TicketRegreso;
			}
			set
			{
				if ((this._TicketRegreso != value))
				{
					if (this._TICKET1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTicketRegresoChanging(value);
					this.SendPropertyChanging();
					this._TicketRegreso = value;
					this.SendPropertyChanged("TicketRegreso");
					this.OnTicketRegresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoEquipaje", DbType="Float NOT NULL")]
		public double PesoEquipaje
		{
			get
			{
				return this._PesoEquipaje;
			}
			set
			{
				if ((this._PesoEquipaje != value))
				{
					this.OnPesoEquipajeChanging(value);
					this.SendPropertyChanging();
					this._PesoEquipaje = value;
					this.SendPropertyChanged("PesoEquipaje");
					this.OnPesoEquipajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVoleto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVoleto
		{
			get
			{
				return this._IdVoleto;
			}
			set
			{
				if ((this._IdVoleto != value))
				{
					this.OnIdVoletoChanging(value);
					this.SendPropertyChanging();
					this._IdVoleto = value;
					this.SendPropertyChanged("IdVoleto");
					this.OnIdVoletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TICKET_VOLETO", Storage="_TICKET", ThisKey="TicketIda", OtherKey="CodigoTicket", IsForeignKey=true)]
		public TICKET TICKET
		{
			get
			{
				return this._TICKET.Entity;
			}
			set
			{
				TICKET previousValue = this._TICKET.Entity;
				if (((previousValue != value) 
							|| (this._TICKET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TICKET.Entity = null;
						previousValue.VOLETO.Remove(this);
					}
					this._TICKET.Entity = value;
					if ((value != null))
					{
						value.VOLETO.Add(this);
						this._TicketIda = value.CodigoTicket;
					}
					else
					{
						this._TicketIda = default(int);
					}
					this.SendPropertyChanged("TICKET");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PASAJEROS_VOLETO", Storage="_PASAJEROS", ThisKey="Pasajero", OtherKey="Identificacion", IsForeignKey=true)]
		public PASAJEROS PASAJEROS
		{
			get
			{
				return this._PASAJEROS.Entity;
			}
			set
			{
				PASAJEROS previousValue = this._PASAJEROS.Entity;
				if (((previousValue != value) 
							|| (this._PASAJEROS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PASAJEROS.Entity = null;
						previousValue.VOLETO.Remove(this);
					}
					this._PASAJEROS.Entity = value;
					if ((value != null))
					{
						value.VOLETO.Add(this);
						this._Pasajero = value.Identificacion;
					}
					else
					{
						this._Pasajero = default(string);
					}
					this.SendPropertyChanged("PASAJEROS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TICKET_VOLETO1", Storage="_TICKET1", ThisKey="TicketRegreso", OtherKey="CodigoTicket", IsForeignKey=true)]
		public TICKET TICKET1
		{
			get
			{
				return this._TICKET1.Entity;
			}
			set
			{
				TICKET previousValue = this._TICKET1.Entity;
				if (((previousValue != value) 
							|| (this._TICKET1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TICKET1.Entity = null;
						previousValue.VOLETO1.Remove(this);
					}
					this._TICKET1.Entity = value;
					if ((value != null))
					{
						value.VOLETO1.Add(this);
						this._TicketRegreso = value.CodigoTicket;
					}
					else
					{
						this._TicketRegreso = default(Nullable<int>);
					}
					this.SendPropertyChanged("TICKET1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class clientesFrecuentesResult
	{
		
		private string _Identificacion;
		
		private string _Nombre;
		
		private System.Nullable<int> _Millas;
		
		public clientesFrecuentesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Millas", DbType="Int")]
		public System.Nullable<int> Millas
		{
			get
			{
				return this._Millas;
			}
			set
			{
				if ((this._Millas != value))
				{
					this._Millas = value;
				}
			}
		}
	}
	
	public partial class vuelosPilotoResult
	{
		
		private string _Origen;
		
		private string _Destino;
		
		private System.DateTime _Fecha_Hora_Viaje;
		
		private System.TimeSpan _Duración;
		
		private string _Aeronave;
		
		private int _Pasajeros;
		
		private string _Piloto;
		
		private string _Temporada;
		
		private int _Referencia;
		
		public vuelosPilotoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this._Origen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this._Destino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Hora Viaje]", Storage="_Fecha_Hora_Viaje", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora_Viaje
		{
			get
			{
				return this._Fecha_Hora_Viaje;
			}
			set
			{
				if ((this._Fecha_Hora_Viaje != value))
				{
					this._Fecha_Hora_Viaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="Time NOT NULL")]
		public System.TimeSpan Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aeronave", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Aeronave
		{
			get
			{
				return this._Aeronave;
			}
			set
			{
				if ((this._Aeronave != value))
				{
					this._Aeronave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasajeros", DbType="Int NOT NULL")]
		public int Pasajeros
		{
			get
			{
				return this._Pasajeros;
			}
			set
			{
				if ((this._Pasajeros != value))
				{
					this._Pasajeros = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piloto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Piloto
		{
			get
			{
				return this._Piloto;
			}
			set
			{
				if ((this._Piloto != value))
				{
					this._Piloto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporada", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Temporada
		{
			get
			{
				return this._Temporada;
			}
			set
			{
				if ((this._Temporada != value))
				{
					this._Temporada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="Int NOT NULL")]
		public int Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
	}
	
	public partial class clientesIdaVueltaResult
	{
		
		private string _Identificacion;
		
		private string _Nombre;
		
		private string _Origen;
		
		private string _Destino;
		
		private decimal _Valor;
		
		public clientesIdaVueltaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this._Origen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this._Destino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Money NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this._Valor = value;
				}
			}
		}
	}
	
	public partial class listarVuelosResult
	{
		
		private string _Origen;
		
		private string _Destino;
		
		private System.DateTime _Fecha_Hora_Viaje;
		
		private System.TimeSpan _Duración;
		
		private string _Aeronave;
		
		private string _Piloto;
		
		private string _Temporada;
		
		private string _Precio_Base;
		
		private int _Referencia;
		
		public listarVuelosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this._Origen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this._Destino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Hora Viaje]", Storage="_Fecha_Hora_Viaje", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora_Viaje
		{
			get
			{
				return this._Fecha_Hora_Viaje;
			}
			set
			{
				if ((this._Fecha_Hora_Viaje != value))
				{
					this._Fecha_Hora_Viaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="Time NOT NULL")]
		public System.TimeSpan Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aeronave", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Aeronave
		{
			get
			{
				return this._Aeronave;
			}
			set
			{
				if ((this._Aeronave != value))
				{
					this._Aeronave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piloto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Piloto
		{
			get
			{
				return this._Piloto;
			}
			set
			{
				if ((this._Piloto != value))
				{
					this._Piloto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporada", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Temporada
		{
			get
			{
				return this._Temporada;
			}
			set
			{
				if ((this._Temporada != value))
				{
					this._Temporada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Precio Base]", Storage="_Precio_Base", DbType="VarChar(30)")]
		public string Precio_Base
		{
			get
			{
				return this._Precio_Base;
			}
			set
			{
				if ((this._Precio_Base != value))
				{
					this._Precio_Base = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="Int NOT NULL")]
		public int Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
	}
	
	public partial class listarVuelosRegistroResult
	{
		
		private int _IdVuelo;
		
		private string _Trayecto;
		
		public listarVuelosRegistroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVuelo", DbType="Int NOT NULL")]
		public int IdVuelo
		{
			get
			{
				return this._IdVuelo;
			}
			set
			{
				if ((this._IdVuelo != value))
				{
					this._IdVuelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trayecto", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Trayecto
		{
			get
			{
				return this._Trayecto;
			}
			set
			{
				if ((this._Trayecto != value))
				{
					this._Trayecto = value;
				}
			}
		}
	}
	
	public partial class registrarTicketResult
	{
		
		private string _Identificacion;
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Contrasenia;
		
		private System.Nullable<int> _Millas;
		
		private System.Nullable<bool> _Frecuente;
		
		public registrarTicketResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Contrasenia
		{
			get
			{
				return this._Contrasenia;
			}
			set
			{
				if ((this._Contrasenia != value))
				{
					this._Contrasenia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Millas", DbType="Int")]
		public System.Nullable<int> Millas
		{
			get
			{
				return this._Millas;
			}
			set
			{
				if ((this._Millas != value))
				{
					this._Millas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuente", DbType="Bit")]
		public System.Nullable<bool> Frecuente
		{
			get
			{
				return this._Frecuente;
			}
			set
			{
				if ((this._Frecuente != value))
				{
					this._Frecuente = value;
				}
			}
		}
	}
	
	public partial class vuelosPasajeroResult
	{
		
		private string _Origen;
		
		private string _Destino;
		
		private System.DateTime _Fecha_Hora_Viaje;
		
		private System.TimeSpan _Duración;
		
		private string _Aeronave;
		
		private string _Temporada;
		
		private string _Precio_Base;
		
		private System.Nullable<int> _Asientos;
		
		private int _Referencia;
		
		public vuelosPasajeroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this._Origen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this._Destino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Hora Viaje]", Storage="_Fecha_Hora_Viaje", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora_Viaje
		{
			get
			{
				return this._Fecha_Hora_Viaje;
			}
			set
			{
				if ((this._Fecha_Hora_Viaje != value))
				{
					this._Fecha_Hora_Viaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="Time NOT NULL")]
		public System.TimeSpan Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aeronave", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Aeronave
		{
			get
			{
				return this._Aeronave;
			}
			set
			{
				if ((this._Aeronave != value))
				{
					this._Aeronave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temporada", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Temporada
		{
			get
			{
				return this._Temporada;
			}
			set
			{
				if ((this._Temporada != value))
				{
					this._Temporada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Precio Base]", Storage="_Precio_Base", DbType="VarChar(30)")]
		public string Precio_Base
		{
			get
			{
				return this._Precio_Base;
			}
			set
			{
				if ((this._Precio_Base != value))
				{
					this._Precio_Base = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asientos", DbType="Int")]
		public System.Nullable<int> Asientos
		{
			get
			{
				return this._Asientos;
			}
			set
			{
				if ((this._Asientos != value))
				{
					this._Asientos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="Int NOT NULL")]
		public int Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
